using FactoryPulse.Reporting.Models;
using iText.Kernel.Colors;
using iText.Kernel.Font;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;

namespace FactoryPulse.Reporting.Services;

public class PdfReportService
{
    private static readonly Color HeaderBg  = new DeviceRgb(30, 60, 90);
    private static readonly Color PassColor = new DeviceRgb(39, 174, 96);
    private static readonly Color FailColor = new DeviceRgb(192, 57, 43);
    private static readonly Color WarnColor = new DeviceRgb(230, 126, 34);
    private static readonly Color RowAlt    = new DeviceRgb(245, 247, 250);

    public byte[] GenerateInspectionReport(
        List<InspectionRecord> inspections,
        DateTime from,
        DateTime to,
        string generatedBy)
    {
        using var stream = new MemoryStream();
        using var writer = new PdfWriter(stream);
        using var pdf    = new PdfDocument(writer);
        using var doc    = new Document(pdf);

        doc.SetMargins(40, 40, 40, 40);

        // --- Header ---
        var title = new Paragraph("FactoryPulse — Inspection Report")
            .SetFontSize(20)
            .SetBold()
            .SetFontColor(ColorConstants.WHITE)
            .SetBackgroundColor(HeaderBg)
            .SetPaddingLeft(12)
            .SetPaddingTop(8)
            .SetPaddingBottom(8);
        doc.Add(title);

        var meta = new Paragraph(
            $"Period: {from:dd MMM yyyy} – {to:dd MMM yyyy}   |   " +
            $"Generated: {DateTime.UtcNow:dd MMM yyyy HH:mm} UTC   |   " +
            $"By: {generatedBy}   |   Records: {inspections.Count}")
            .SetFontSize(9)
            .SetFontColor(ColorConstants.DARK_GRAY)
            .SetMarginBottom(16);
        doc.Add(meta);

        // --- Summary boxes ---
        int pass  = inspections.Count(i => i.Result == "Pass");
        int fail  = inspections.Count(i => i.Result == "Fail");
        int warn  = inspections.Count(i => i.Result == "NeedsAttention");

        var summaryTable = new Table(UnitValue.CreatePercentArray([25f, 25f, 25f, 25f]))
            .UseAllAvailableWidth()
            .SetMarginBottom(20);

        summaryTable.AddCell(SummaryCell("Total",            inspections.Count.ToString(), ColorConstants.DARK_GRAY));
        summaryTable.AddCell(SummaryCell("Pass",             pass.ToString(),              PassColor));
        summaryTable.AddCell(SummaryCell("Fail",             fail.ToString(),              FailColor));
        summaryTable.AddCell(SummaryCell("Needs Attention",  warn.ToString(),              WarnColor));
        doc.Add(summaryTable);

        // --- Inspections table ---
        var table = new Table(UnitValue.CreatePercentArray([8f, 22f, 18f, 16f, 16f, 20f]))
            .UseAllAvailableWidth();

        foreach (var header in new[] { "ID", "Equipment", "Location", "Inspector", "Result", "Date" })
        {
            table.AddHeaderCell(new Cell()
                .Add(new Paragraph(header).SetBold().SetFontSize(9).SetFontColor(ColorConstants.WHITE))
                .SetBackgroundColor(HeaderBg)
                .SetPaddingTop(6).SetPaddingBottom(6).SetPaddingLeft(6));
        }

        for (int i = 0; i < inspections.Count; i++)
        {
            var insp = inspections[i];
            var bg   = i % 2 == 0 ? ColorConstants.WHITE : RowAlt;

            Color resultColor = insp.Result switch
            {
                "Pass"           => PassColor,
                "Fail"           => FailColor,
                "NeedsAttention" => WarnColor,
                _                => ColorConstants.BLACK
            };

            table.AddCell(BodyCell(insp.Id.ToString(), bg));
            table.AddCell(BodyCell(insp.EquipmentName, bg));
            table.AddCell(BodyCell(insp.EquipmentLocation, bg));
            table.AddCell(BodyCell(insp.InspectorName, bg));
            table.AddCell(new Cell()
                .Add(new Paragraph(insp.Result).SetFontSize(9).SetBold().SetFontColor(resultColor))
                .SetBackgroundColor(bg).SetPaddingTop(5).SetPaddingBottom(5).SetPaddingLeft(6));
            table.AddCell(BodyCell(insp.CreatedAt.ToString("dd/MM/yyyy HH:mm"), bg));
        }

        doc.Add(table);

        // Footer note
        doc.Add(new Paragraph("This report is auto-generated by FactoryPulse. Do not alter without authorization.")
            .SetFontSize(8)
            .SetFontColor(ColorConstants.LIGHT_GRAY)
            .SetMarginTop(20)
            .SetTextAlignment(TextAlignment.CENTER));

        doc.Close();
        return stream.ToArray();
    }

    private static Cell SummaryCell(string label, string value, Color color)
    {
        return new Cell()
            .Add(new Paragraph(label).SetFontSize(9).SetFontColor(ColorConstants.DARK_GRAY))
            .Add(new Paragraph(value).SetFontSize(22).SetBold().SetFontColor(color))
            .SetPaddingLeft(10).SetPaddingTop(8).SetPaddingBottom(8)
            .SetBorder(new iText.Layout.Borders.SolidBorder(ColorConstants.LIGHT_GRAY, 1));
    }

    private static Cell BodyCell(string text, Color bg)
    {
        return new Cell()
            .Add(new Paragraph(text).SetFontSize(9))
            .SetBackgroundColor(bg)
            .SetPaddingTop(5).SetPaddingBottom(5).SetPaddingLeft(6);
    }
}
